#pragma once

// Version info - auto-generated by MakeVersionInfo

namespace Version
{
    constexpr unsigned major = 1;
    constexpr unsigned minor = 0;
    constexpr unsigned revision = 5;
    constexpr unsigned build = 14;
    constexpr char commit[] = "g8f9f292";
    constexpr bool isDevBuild = 1;
    constexpr char name[] = "1.0.5.14-g8f9f292-dev";
    constexpr char date[] = "2024-04-14";
    constexpr char time[] = "2024-04-14T22:02:56.296421+00:00";
    constexpr unsigned langVersion = cppVersion;
    constexpr const char* langCompiler = compilerName;
}
